name: hpack
version: 0.14.1
synopsis: An alternative format for Haskell packages
maintainer: Simon Hengel <sol@typeful.net>
license: MIT
github: sol/hpack
category: Development

ghc-options: -Wall

dependencies:
  - base >= 4.7 && < 5
  - base-compat >= 0.8
  - Cabal
  - pretty
  - deepseq
  - directory
  - filepath
  - Glob
  - text
  - containers
  - unordered-containers
  - yaml
  - bytestring
  - vector

library:
  source-dirs: src
  dependencies:
    - aeson >= 0.8
  exposed-modules:
    - Hpack
    - Hpack.Config
    - Hpack.Run
    - Hpack.Yaml

executables:
  hpack:
    main: Main.hs
    source-dirs: driver
    dependencies:
      - hpack
      - aeson >= 0.8

tests:
  spec:
    cpp-options: -DTEST
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec == 2.*
      - QuickCheck
      - temporary
      - mockery >= 0.3
      - interpolate
      - aeson-qq
      - aeson >= 0.10
