name: hpack
version: 0.35.2
synopsis: A modern format for Haskell packages
description: See README at <https://github.com/sol/hpack#readme>
maintainer: Simon Hengel <sol@typeful.net>
github: sol/hpack
category: Development
extra-source-files:
  - CHANGELOG.md
  - resources/**/*

ghc-options: -Wall -fno-warn-incomplete-uni-patterns

dependencies:
  - base
  - bytestring
  - deepseq
  - directory
  - filepath
  - Glob
  - text
  - containers
  - unordered-containers
  - yaml
  - aeson
  - scientific
  - Cabal
  - pretty
  - bifunctors
  - cryptonite
  - transformers
  - http-types
  - http-client
  - http-client-tls
  - vector
  - infer-license

library:
  source-dirs: src
  exposed-modules:
    - Hpack
    - Hpack.Config
    - Hpack.Render
    - Hpack.Yaml
    - Hpack.Error

executable:
  main: Main.hs
  source-dirs: driver
  dependencies:
    - hpack

tests:
  spec:
    cpp-options: -DTEST
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec
      - QuickCheck
      - temporary
      - mockery 
      - interpolate
      - template-haskell
      - HUnit
    build-tools: hspec-discover
